services:
  - type: web
    name: trackr-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: trackr-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: trackr-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: trackr-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: trackr-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: trackr-db
          property: database
      - key: SERVER_PORT
        value: 8080

databases:
  - name: trackr-db
    plan: free
    databaseName: trackr
    user: trackr_user
